---
dotfiles_mode: apply
dotfiles_repo_root: "{{ playbook_dir | dirname }}"
dotfiles_stow_target: "{{ ansible_env.HOME }}"
dotfiles_apps_root: "{{ ansible_env.HOME }}/apps"
dotfiles_local_bin_dir: "{{ ansible_env.HOME }}/.local/bin"
dotfiles_local_scripts_dir: "{{ ansible_env.HOME }}/.local/scripts"
dotfiles_share_root: "{{ ansible_env.HOME }}/.local/share"
dotfiles_stow_packages_common:
  - ssh
  - nvim
  - tmux
  - zsh
  - bin
  - ghostty

dotfiles_stow_packages_linux_desktop:
  - i3
  - i3status
  - picom

dotfiles_common_linux_packages:
  - git
  - curl
  - ca-certificates
  - stow
  - zsh
  - tmux
  - neovim
  - fzf
  - ripgrep
  - fd
  - age
  - gh
  - unzip
  - xclip
  - build_tools
  - python
  - xterm_terminal

dotfiles_common_macos_packages:
  - git
  - curl
  - stow
  - zsh
  - tmux
  - neovim
  - fzf
  - ripgrep
  - fd
  - age
  - gh
  - starship

dotfiles_starship_enabled: true
dotfiles_uv_enabled: true
dotfiles_uv_root: "{{ dotfiles_apps_root }}/uv"
dotfiles_uv_bin_dir: "{{ dotfiles_uv_root }}/bin"
dotfiles_fnm_enabled: true
dotfiles_fnm_dir: "{{ dotfiles_share_root }}/fnm"
dotfiles_node_lts_enabled: true
