---
dotfiles_linux_pkg_map:
  git:
    - git
  curl:
    - curl
  ca-certificates:
    - ca-certificates
  stow:
    - stow
  zsh:
    - zsh
  tmux:
    - tmux
  neovim:
    - neovim
  fzf:
    - fzf
  ripgrep:
    - ripgrep
  age:
    - age
  gh:
    - gh
  delta:
    - git-delta
  btop:
    - btop
  unzip:
    - unzip
  jq:
    - jq
  rsync:
    - rsync
  netcat:
    - netcat-openbsd
  lsof:
    - lsof
  patch:
    - patch
  openssh_client:
    - openssh-client
  wireguard_tools:
    - wireguard
  build_tools:
    - build-essential
  fd:
    - fd-find
  python:
    - python3
    - python3-pip
    - python3-venv
  sway:
    - sway
  swaylock:
    - swaylock
  swayidle:
    - swayidle
  swaybg:
    - swaybg
  kanshi:
    - kanshi
  i3status:
    - i3status
  grim:
    - grim
  slurp:
    - slurp
  wl_clipboard:
    - wl-clipboard
  brightnessctl:
    - brightnessctl
  mako_notifier:
    - mako-notifier
  xdg_desktop_portal:
    - xdg-desktop-portal
  xdg_desktop_portal_wlr:
    - xdg-desktop-portal-wlr
  foot:
    - foot
  pavucontrol:
    - pavucontrol
  thunar:
    - thunar
  rofi:
    - rofi
  dex:
    - dex
  nm_applet:
    - network-manager-gnome
  jetbrains_mono_fonts:
    - fonts-jetbrains-mono
