---
dotfiles_linux_pkg_map:
  git:
    - git
  curl:
    - curl
  ca-certificates:
    - ca-certificates
  stow:
    - stow
  zsh:
    - zsh
  tmux:
    - tmux
  neovim:
    - neovim
  fzf:
    - fzf
  ripgrep:
    - ripgrep
  age:
    - age
  gh:
    - github-cli
  delta:
    - git-delta
  btop:
    - btop
  unzip:
    - unzip
  wireguard_tools:
    - wireguard-tools
  build_tools:
    - gcc
    - make
  fd:
    - fd
  python:
    - python
    - python-pip
  sway:
    - sway
  swaylock:
    - swaylock
  swayidle:
    - swayidle
  swaybg:
    - swaybg
  i3status:
    - i3status
  grim:
    - grim
  slurp:
    - slurp
  wl_clipboard:
    - wl-clipboard
  brightnessctl:
    - brightnessctl
  mako_notifier:
    - mako
  xdg_desktop_portal:
    - xdg-desktop-portal
  xdg_desktop_portal_wlr:
    - xdg-desktop-portal-wlr
  foot:
    - foot
  pavucontrol:
    - pavucontrol
  thunar:
    - thunar
  rofi:
    - rofi
  dex:
    - dex
  nm_applet:
    - network-manager-applet
  jetbrains_mono_fonts:
    - ttf-jetbrains-mono
