---
dotfiles_linux_pkg_map:
  git:
    - git
  curl:
    - curl
  ca-certificates:
    - ca-certificates
  stow:
    - stow
  zsh:
    - zsh
  tmux:
    - tmux
  neovim:
    - neovim
  fzf:
    - fzf
  ripgrep:
    - ripgrep
  age:
    - age
  unzip:
    - unzip
  build_tools:
    - gcc
    - gcc-c++
    - make
  fd:
    - fd
  python:
    - python3
    - python3-pip
  i3:
    - i3
  i3status:
    - i3status
  i3lock:
    - i3lock
  xss-lock: []
  feh:
    - feh
  pavucontrol:
    - pavucontrol
  thunar:
    - thunar
  rofi:
    - rofi
  picom:
    - picom
  dex:
    - dex
  nm_applet:
    - NetworkManager-applet
  jetbrains_mono_fonts:
    - jetbrains-mono-fonts
  xterm_terminal:
    - xterm
