---
dotfiles_profile_linux_packages_common:
  - sway
  - swaylock
  - swayidle
  - swaybg
  - kanshi
  - waybar
  - grim
  - slurp
  - wl_clipboard
  - brightnessctl
  - mako_notifier
  - xdg_desktop_portal
  - xdg_desktop_portal_wlr
  - xdg_desktop_portal_gtk
  - foot
  - pipewire
  - wireplumber
  - pipewire_pulse
  - pipewire_alsa
  - pipewire_jack
  - pavucontrol
  - bluez
  - blueman
  - power_profiles_daemon
  - plocate
  - upower
  - nautilus
  - gvfs_mtp
  - gvfs_smb
  - gvfs_nfs
  - ffmpegthumbnailer
  - webp_pixbuf_loader
  - mate_polkit
  - gnome_keyring
  - swayosd
  - playerctl
  - zram_generator_defaults
  - mpv
  - imv
  - rofi
  - dex
  - nm_applet
  - jetbrains_mono_fonts
  - nerd_fonts
  - noto_color_emoji_fonts
  - noto_sans_cjk_fonts
  - adwaita_icon_theme
